kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: build
    image: golang
    commands:
      - go build
      - go test ./...

  - name: test
    image: golang
    commands:
      - go install github.com/jstemmer/go-junit-report/v2@latest
      - go test -v 2>&1 ./... | go-junit-report -set-exit-code > testdata/live-report.xml

  - name: junit-latest
    image: boringdownload/drone-junit:latest
    depends_on:
      - test
    settings:
      paths: testdata/*.xml
      report_name: my-tests
    when:
      branch:
        - main

  - name: junit-alpha
    image: boringdownload/drone-junit:alpha
    depends_on:
      - test
    settings:
      paths: testdata/*.xml
      report_name: my-tests
