kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test ./...

- name: publish
  image: plugins/docker
  settings:
    repo: boringdownload/drone-junit
    auto_tag: true
    dockerfile: docker/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
